version: "3.9"

services:
  web:
    build: .
    command: php -S 0.0.0.0:8888
    volumes: 
      - ./src:/code
      - ./output:/output
      - ./uploads:/uploads
    ports:
      - "8888:8888"
      